apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: wlsdn2165/ask-anything-post:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: SPRING_R2DBC_URL
              value: r2dbc:mysql://ask-anything-db:3306/ask_anything
            - name: SPRING_R2DBC_USERNAME
              value: root
            - name: SPRING_R2DBC_PASSWORD
              value: root

---
apiVersion: v1
kind: Service
metadata:
  name: ask-anything-post
spec:
  selector:
    app: post
  ports:
    - port: 8040
      targetPort: 8080
      protocol: TCP
  clusterIP: None
