server:
  port: 8040

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ask_anything?serverTimezone=UTC&characterEncoding=UTF-8
    username: {mysql_user}
    password: {mysql_password}