server:
  port: 8040

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
    username: sa
    password: