apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
    app: ask-anything
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: ask-anything
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ask-anything-db
  labels:
    app: ask-anything
spec:
  ports:
    - port: 3306
  selector:
    app: ask-anything
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ask-anything-db
  labels:
    app: ask-anything
spec:
  selector: # mySQL Pod Should contain same labels
    matchLabels:
      app: ask-anything
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: ask-anything
    spec:
      containers:
        - name: ask-anything-db
          image: mysql:8.0.30
          imagePullPolicy: "IfNotPresent"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: mysql-initdb
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
        - name: mysql-persistance-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  labels:
    app: ask-anything
data:
  initdb.sql: |
    CREATE database ask_anything;
    use ask_anything;
    CREATE TABLE `user` (`user_id` bigint NOT NULL AUTO_INCREMENT, `user_name` varchar(50) NOT NULL, `email` varchar(50) NOT NULL, PRIMARY KEY (`user_id`)) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    CREATE TABLE `post` (`post_id` bigint NOT NULL AUTO_INCREMENT, `title` varchar(50) NOT NULL, `text` varchar(255) NOT NULL, `created_at` datetime NOT NULL, `modified_at` datetime NOT NULL, `user_id` bigint NOT NULL, PRIMARY KEY (`post_id`), KEY `user_id` (`user_id`), CONSTRAINT `user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;